In [20]:
import pandas as pd

In [21]:
movie_df= pd.read_csv('sound_track_imdb_top_250_movie_tv_series.csv',sep=',')

In [22]:
movie_df.columns

Index(['Unnamed: 0', 'name', 'year', 'song_name', 'written_by', 'performed_by',
       'composed_by', 'lyrics_by', 'written_performed_by', 'music_by',
       'courtesy_of', 'conducted_by', 'libretto_by', 'under_license_from'],
      dtype='object')

In [23]:
#remove rows we won't use
movie_df=movie_df.drop(columns=['Unnamed: 0','written_by','composed_by','lyrics_by','written_performed_by','music_by','courtesy_of','conducted_by','libretto_by','under_license_from'])

In [24]:
movie_df
#3133 rows incluiding all data

,name,year,song_name,performed_by
0,The Shawshank Redemption,1994,If I Didn't Care,The Ink Spots
1,The Shawshank Redemption,1994,Duettino - Sull'aria,Edith Mathis (uncredited) and Gundula Janowitz...
2,The Shawshank Redemption,1994,Put The Blame On Mame,NaN
3,The Shawshank Redemption,1994,Lovesick Blues,Hank Williams
4,The Shawshank Redemption,1994,Willie and The Hand Jive,NaN
...,...,...,...,...
3128,"Love, Death & Robots",2019,It looks like we don't have any Soundtracks fo...,NaN
3129,Foyle's War,2002,It looks like we don't have any Soundtracks fo...,NaN
3130,Jesus of Nazareth,1977,It looks like we don't have any Soundtracks fo...,NaN
3131,Luther,2010,Paradise Circus,Massive Attack
3132,Ethos,2020,It looks like we don't have any Soundtracks fo...,NaN

In [25]:
#Remove all rows that have the text "it looks like we don't have any soundtracks for this title yet"

text= "It looks like we don't have any Soundtracks for this title yet."
movie_df=movie_df[movie_df['song_name']!=text]

In [26]:
#new dataframe with 2956 rows 
movie_df

,name,year,song_name,performed_by
0,The Shawshank Redemption,1994,If I Didn't Care,The Ink Spots
1,The Shawshank Redemption,1994,Duettino - Sull'aria,Edith Mathis (uncredited) and Gundula Janowitz...
2,The Shawshank Redemption,1994,Put The Blame On Mame,NaN
3,The Shawshank Redemption,1994,Lovesick Blues,Hank Williams
4,The Shawshank Redemption,1994,Willie and The Hand Jive,NaN
...,...,...,...,...
3123,Flames,2018,Khamoshiyan,Kumar Sanu and Alka Yagnik
3125,Modern Family,2009,Circle Of Life,Elton John
3126,Modern Family,2009,Modern Family Main Theme,NaN
3127,Modern Family,2009,We're All In This Together,Ty Burrell
3131,Luther,2010,Paradise Circus,Massive Attack

In [27]:
movie_df[movie_df['performed_by'].isna()]

,name,year,song_name,performed_by
2,The Shawshank Redemption,1994,Put The Blame On Mame,NaN
4,The Shawshank Redemption,1994,Willie and The Hand Jive,NaN
6,The Godfather,1972,Mall Wedding Sequence,NaN
11,The Godfather,1972,Santa Claus Is Coming To Town,NaN
12,The Godfather,1972,The Bells of St. Mary's,NaN
...,...,...,...,...
3118,Your Lie in April,2014,"Ballade nÂº1 in G minor, Op.23",NaN
3119,Flames,2018,Lamha,NaN
3120,Flames,2018,Lamha (acoustic),NaN
3122,Flames,2018,Kuch to Dil,NaN
3126,Modern Family,2009,Modern Family Main Theme,NaN

In [33]:
movie_df[movie_df.duplicated('name')]

,name,year,song_name,performed_by
1,The Shawshank Redemption,1994,Duettino - Sull'aria,Edith Mathis (uncredited) and Gundula Janowitz...
2,The Shawshank Redemption,1994,Put The Blame On Mame,NaN
3,The Shawshank Redemption,1994,Lovesick Blues,Hank Williams
4,The Shawshank Redemption,1994,Willie and The Hand Jive,NaN
5,The Shawshank Redemption,1994,A Mighty Fortress Is Our God,Bob Gunton
...,...,...,...,...
3121,Flames,2018,Thame Dil Ko,Abhijeet
3122,Flames,2018,Kuch to Dil,NaN
3123,Flames,2018,Khamoshiyan,Kumar Sanu and Alka Yagnik
3126,Modern Family,2009,Modern Family Main Theme,NaN
3127,Modern Family,2009,We're All In This Together,Ty Burrell

In [17]:
movie_df.to_csv('new_movie_df.csv',sep=',',index=False)