In [39]:
import pandas as pd
import numpy as np

read csv

In [40]:
df = pd.read_csv('..\\data\\sound_track_imdb_top_250_movie_tv_series.csv', delimiter=",", index_col=0)

In [41]:
df.columns

Index(['name', 'year', 'song_name', 'written_by', 'performed_by',
       'composed_by', 'lyrics_by', 'written_performed_by', 'music_by',
       'courtesy_of', 'conducted_by', 'libretto_by', 'under_license_from'],
      dtype='object')

select the needed columns and create new df

In [42]:
df_selected = df.loc[:,['name','year','song_name','performed_by']]
df_selected

,name,year,song_name,performed_by
0,The Shawshank Redemption,1994,If I Didn't Care,The Ink Spots
1,The Shawshank Redemption,1994,Duettino - Sull'aria,Edith Mathis (uncredited) and Gundula Janowitz...
2,The Shawshank Redemption,1994,Put The Blame On Mame,NaN
3,The Shawshank Redemption,1994,Lovesick Blues,Hank Williams
4,The Shawshank Redemption,1994,Willie and The Hand Jive,NaN
...,...,...,...,...
3128,"Love, Death & Robots",2019,It looks like we don't have any Soundtracks fo...,NaN
3129,Foyle's War,2002,It looks like we don't have any Soundtracks fo...,NaN
3130,Jesus of Nazareth,1977,It looks like we don't have any Soundtracks fo...,NaN
3131,Luther,2010,Paradise Circus,Massive Attack
3132,Ethos,2020,It looks like we don't have any Soundtracks fo...,NaN

In [43]:
# df_selected['performed_by'].isna().sum()

In [44]:
# filter_mask = df_selected['song_name'] == "It looks like we don't have any Soundtracks for this title yet."
# filter_mask.sum()

In [45]:
# df_selected[filter_mask]

replace "it looks like we don't ...." with NaN

In [46]:
df_selected.replace("It looks like we don't have any Soundtracks for this title yet.", "Not available", inplace=True)

write df_selected to csv file

In [47]:
# df_selected.to_csv("..\\data\\filtered_movie_songs.csv")

In [52]:
df_selected.groupby('song_name').count()

                                                    name  year  performed_by
song_name
'Andante' from 'Sonata No. 1 In G Major, BWV 10...     1     1             1
'Branded' Theme Song                                   1     1             0
'Summertime' from 'Porgy and Bess'                     1     1             0
'The Itchy & Scratchy Show' Theme                      1     1             1
'Variatio 25' of 'The Goldberg Variations'             1     1             1
...                                                  ...   ...           ...
Ã‡a Plane Pour Moi                                      1     1             1
Ã‰cole BuissonniÃ¨re                                     1     1             0
Ã‰tude Op. 25, No. 11 in A minor ('Winter Wind')        1     1             0
ÃŠ Baiana                                               1     1             1
Ã–det Ã„r en Rackare                                     1     1             0

[2787 rows x 3 columns]

find duplicate songs

In [61]:
duplicates = df_selected['song_name'].duplicated(keep=False)
duplicate_songs_df = df_selected[duplicates]
duplicate_songs_df = duplicate_songs_df.sort_values(by='song_name')
duplicate_songs_df

,name,year,song_name,performed_by
526,Apocalypse Now,1979,(I Can't Get No) Satisfaction,The Rolling Stones
1468,Casino,1995,(I Can't Get No) Satisfaction,The Rolling Stones
1517,Casino,1995,(I Can't Get No) Satisfaction,Devo
654,American Beauty,1999,All Along The Watchtower,NaN
106,Forrest Gump,1994,All Along The Watchtower,The Jimi Hendrix Experience
...,...,...,...,...
752,Toy Story,1995,You've Got a Friend in Me,Randy Newman & Lyle Lovett
1680,No Country for Old Men,2007,Young Men Dead,The Black Angels
2679,True Detective,2014,Young Men Dead,NaN
2172,Mary and Max,2009,Zorba's Dance,The London Pops Orchestra
1783,"Lock, Stock and Two Smoking Barrels",1998,Zorba's Dance,David A. Hughes and John Murphy

In [78]:
df[df['conducted_by'].notnull()].isna().sum()

# df.notna().sum()

name                      0
year                      0
song_name                 0
written_by               74
performed_by              9
composed_by              92
lyrics_by               105
written_performed_by    107
music_by                 70
courtesy_of              62
conducted_by              0
libretto_by             100
under_license_from      102
dtype: int64